import Home from './Home/OldHome';
import HomeNuevo from './Home/HomeNuevo';
import Landing from './Landing/Landing';
import Login from './Login/Login';
import DoctorsList from './DoctorsList/DoctorsList';
import DoctorDetail from './DoctorDetail/DoctorDetail';
import CreatePatient from './CreatePatient/CreatePatient';
import PatientPanel from './PatientPanel/PatientPanel';
import LoginMedico from './Login Medico/LoginMedico';
export { Home, HomeNuevo, Landing, Login, DoctorsList, DoctorDetail, LoginMedico, CreatePatient, PatientPanel };
